TracNghiem/Models/QuizTest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TracNghiem.Models
{
    public class QuizTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizTest()
        {
            Quiz = new HashSet<Quiz>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TestID { get; set; }

        [Required]
        public int TotalTime { get; set; }

        [Required]
        public int TotalMark { get; set; }

        [Required]
        [StringLength(100)]
        public string name { get; set; }

        [ForeignKey("Creator")]
        [Required]
        public int CreatorID { get; set; }

        public virtual User Creator { get; set; }

        [ForeignKey("Subject")]
        public int SubjectID { get; set; }

        public virtual Subject Subject { get; set; }

        [Required]
        public TestStatusAd status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quiz { get; set; }
        [Required]
        public DateTime CreateDate { get; set; }
    }
}

TracNghiem/Controllers/QuizTestController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;
using TracNghiem.ViewModel;

namespace TracNghiem.Controllers
{
    [Authorize]
    public class QuizTestController : Controller
    {
        private QuizContext db = new QuizContext();
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Tạo đề thi mới
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "admin,teacher")]
        public ActionResult Create()
        {
            var model = new QuizTestViewModel
            {
                Subject = Common.Helper.getSubjectItem(),
            };
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "admin,teacher")]
        public JsonResult Create(QuizTestViewModel model)
        {
            model.Subject = Common.Helper.getSubjectItem();
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, Message = "Bạn nhập thiếu các trường yêu cầu" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                User u = db.Users.Where(i => i.username == User.Identity.Name).First();

                QuizTest test = new QuizTest
                {
                    CreatorID = u.ID,
                    Creator = u,
                    CreateDate = DateTime.Now,
                    SubjectID = model.SubjectID,
                    TotalMark = model.TotalMark,
                    name = model.name,
                    TotalTime = (int)model.TotalTime,
                    status = (TestStatusAd)model.status,
                };
                foreach(var item in model.quizID)
                {
                    Quiz q = db.Quizzes.Find(item);
                    test.Quiz.Add(q);
                }
                db.QuizTests.Add(test);
                db.SaveChanges();
                return  Json(new { success = true, Message = "Tạo đề thi thành công !" }, JsonRequestBehavior.AllowGet);
            }
            
        }
        /// <summary>
        /// Quản lý đề thi của tôi
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="CurrentSort"></param>
        /// <param name="page"></param>
        /// <param name="titleStr"></param>
        /// <returns></returns>
        public ViewResult MyQuizTest(string sortOrder, string CurrentSort, int? page, string titleStr)
        {
            int pageSize = 100;
            int pageIndex = 1;
            ViewBag.Sort = "tăng dần";
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "Title" : sortOrder;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<QuizTestViewModel> lstQuiz = null;
            var id = db.Users.Where(e => e.username == User.Identity.Name).First().ID;
            if (String.IsNullOrWhiteSpace(titleStr))
            {
                switch (sortOrder)
                {
                    case "title":
                        lstQuiz = db.QuizTests.Where(e => e.CreatorID == id).OrderBy(e => e.name).Select(q =>
                        new QuizTestViewModel
                        {
                            status = (TestStatus)q.status,
                            TestID = q.TestID,
                            name = q.name,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                    case "createdate":
                        lstQuiz = db.QuizTests.Where(e => e.CreatorID == id).OrderBy(e => e.CreateDate).Select(q =>
                        new QuizTestViewModel
                        {
                            status = (TestStatus)q.status,
                            TestID = q.TestID,
                            name = q.name,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                    default:
                        lstQuiz = db.QuizTests.Where(e => e.CreatorID == id).OrderBy(e => e.name).Select(q =>
                        new QuizTestViewModel
                        {
                            status = (TestStatus)q.status,
                            TestID = q.TestID,
                            name = q.name,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                }
            }
            else
            {
                ViewBag.titleStr = titleStr;
                switch (sortOrder)
                {
                    case "title":
                        ViewBag.sortname = "tiêu đề";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            lstQuiz = db.QuizTests.Where(t => t.name.Contains(titleStr) && t.CreatorID == id).OrderBy(e => e.name).Select(q =>
                              new QuizTestViewModel
                              {
                                  status = (TestStatus)q.status,
                                  TestID = q.TestID,
                                  name = q.name,
                                  SubjectName = q.Subject.name,
                                  CreatorName = q.Creator.username,
                                  CreateDate = q.CreateDate,
                              }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        else
                        {
                            lstQuiz = db.QuizTests.Where(t => t.name.Contains(titleStr) && t.CreatorID == id).OrderByDescending(e => e.name).Select(q =>
                           new QuizTestViewModel
                           {
                               status = (TestStatus)q.status,
                               TestID = q.TestID,
                               name = q.name,
                               SubjectName = q.Subject.name,
                               CreatorName = q.Creator.username,
                               CreateDate = q.CreateDate,
                           }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    case "createdate":
                        ViewBag.sortname = "ngày tạo";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            lstQuiz = db.QuizTests.Where(t => t.name.Contains(titleStr) && t.CreatorID == id).OrderBy(e => e.CreateDate).Select(q =>
                            new QuizTestViewModel
                            {
                                status = (TestStatus)q.status,
                                TestID = q.TestID,
                                name = q.name,
                                SubjectName = q.Subject.name,
                                CreatorName = q.Creator.username,
                                CreateDate = q.CreateDate,
                            }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        else
                        {
                            lstQuiz = db.QuizTests.Where(t => t.name.Contains(titleStr) && t.CreatorID == id).OrderByDescending(e => e.CreateDate).Select(q =>
                            new QuizTestViewModel
                            {
                                status = (TestStatus)q.status,
                                TestID = q.TestID,
                                name = q.name,
                                SubjectName = q.Subject.name,
                                CreatorName = q.Creator.username,
                                CreateDate = q.CreateDate,
                            }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    default:
                        lstQuiz = db.QuizTests.Where(t => t.name.Contains(titleStr) && t.CreatorID == id).OrderBy(e => e.name).Select(q =>
                        new QuizTestViewModel
                        {
                            status = (TestStatus)q.status,
                            TestID = q.TestID,
                            name = q.name,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                }
            }
            return View(lstQuiz);
        }
        /// <summary>
        /// Tất cả đề thi (admin)
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="CurrentSort"></param>
        /// <param name="page"></param>
        /// <param name="titleStr"></param>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public ViewResult AllQuizTest(string sortOrder, string CurrentSort, int? page, string titleStr){
            int pageSize = 100;
            int pageIndex = 1;
            ViewBag.Sort = "tăng dần";
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "Title" : sortOrder;

TracNghiem/Views/QuizTest/AllQuizTest.cshtml
@model PagedList.IPagedList<TracNghiem.ViewModel.QuizTestViewModelAd>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Tất Cả Đề Thi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.css" rel="stylesheet" />

<div style="margin-top:10px;"></div>

<div class="row">

    <div class="col-12">
        <div class="card">
            <div style="padding: 0.75rem 1.25rem;">
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div>
                            <label style="display:inline-block;font-weight:normal">Sắp xếp theo <b>@ViewBag.sortname</b> @ViewBag.Sort</label>
                        </div>
                        @Html.ActionLink("Tiêu đề", "AllQuizTest", new { sortOrder = "title", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                        @Html.ActionLink("Ngày tạo", "AllQuizTest", new { sortOrder = "createdate", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                    </div>
                    <div class="col-sm-12 col-md-4">
                        @using (Html.BeginForm("AllQuizTest", "QuizTest", FormMethod.Get, new { enctype = "multipart/form-data" }))
                        {
                            <label style="display:inline-block;font-weight:normal;">
                                Tìm theo tiêu đề:
                                <input name="titleStr" type="search" value="@(ViewBag.titleStr as string)" class="form-control">
                            </label>
                            <label style="display:inline-block;font-weight:normal;">
                                <input style="margin-top:-4.4px" class="btn btn-info" type="submit" value="Tìm kiếm" />
                            </label>
                        }

                    </div>
                    <div class="col-md-3">
                        <br />
                        <a href="/Quiz/MyQuiz" style="font-size: 14px;font-weight: normal;padding: .8em;" class="badge badge-danger">RESET bộ lọc</a>
                        <a href="/QuizTest/Create" style="font-size: 14px;font-weight: normal;padding: .8em;" class="badge badge-info">Thêm Đề</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">

        <div class="card">
            <div class="card-header">
                @if (Model.PageNumber > 1)
                {
                    <h3 class="card-title">
                        100 đề thi thứ @Model.PageNumber
                    </h3>
                }
                else
                {
                    <h3 class="card-title">
                        100 đề thi đầu tiên
                    </h3>
                }
            </div>
            <div class="card-body">
                <table id="lstPost" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên</th>
                            <th>Môn học</th>
                            <th>Người tạo</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <p>@item.TestID</p>
                                </td>
                                <td>
                                    @item.name
                                </td>
                                <td>
                                    @item.CreatorName
                                </td>
                                <td>
                                    @item.SubjectName
                                </td>
                                <td>
                                    @String.Format("{0:dd/MM/yyyy}", item.CreateDate)
                                </td>
                                <td>
                                    <label class="switch">
                                        <input onchange="changeStt(this)" type="checkbox" id="@item.TestID" @(item.status == TracNghiem.Models.TestStatusAd.Active ? "checked" : "") class="success">
                                        <span class="slider"></span>
                                    </label>
                                </td>
                                <td>
                                    @{
                                        if (User.Identity.Name == item.CreatorName || User.IsInRole("admin"))
                                        {
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.TestID }, new { @class = "badge badge-primary" })
                                            <a onclick="deleteConfirm(@item.TestID,'@item.name')" href="#" class="badge badge-danger">Xóa</a>

                                        }
                                    }

                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Tên câu hỏi</th>
                            <th>Độ khó</th>
                            <th>Môn học</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
@{
    if (Model.PageCount > 1)
    {
        <nav aria-label="Page navigation example" style="text-align:center">
            @Html.PagedListPager(Model, page => Url.Action("MyQuiz", new { page, sortOrder = Request.Params["sortOrder"], CurrentSort = Request.Params["CurrentSort"], titleStr = ViewBag.titleStr }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
        </nav>
    }
}
<!-- The delete Modal -->
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Bạn có muốn xóa đề ?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="deleteBtn" class="btn btn-danger">Xóa</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="~/Content/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.min.js"></script>

<script>
    $(function () {
        $("#lstPost").DataTable();
    });
    var delmodal = $('#deleteModal');
    var idx;
    var deleteConfirm = function (id, title) {
        idx = id;
        delmodal.find('.modal-body').text(title);
        delmodal.modal('show');

    }
    $('#deleteBtn').click(function () {
        delmodal.modal('hide');
        $.ajax({
            type: "POST",
            url: '/QuizTest/DeleteQuizTest',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ id: idx }),
            dataType: "json",
            success: function (recData) {
                var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                    type: 'pastel-info',
                    allow_dismiss: false,
                    timer: 1000,
                });
                setTimeout(function () {
                    window.location.reload();
                }, 2000);

            },
            error: function () {
                var notify = $.notify('<strong>Lỗi</strong><br/>Không xóa được<br />', {
                    type: 'pastel-warning',
                    allow_dismiss: false,
                });
            }
        });
    });
    var changeStt = function (xthis) {
        var xid = xthis.id;
        var st = xthis.checked ? 1 : 0;
        $.ajax({
            type: "POST",
            url: '/QuizTest/ChangeStatus',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ id: xid, state: st }),
            dataType: "json",
            success: function (recData) {
                var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                    type: 'pastel-info',
                    allow_dismiss: false,
                    timer: 1000,
                });
            },
            error: function () { alert('An error occured'); }
        });
    }
</script>

TracNghiem/Views/QuizTest/Edit.cshtml
@model TracNghiem.ViewModel.QuizTestViewModel
@{
    ViewBag.Title = "SỬA ĐỀ THI "+Model.name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="overlay" style="display:none;">
    <div class="spinner"></div>
    <br />
    Loading...
</div>
<div class="container-fluid" style="margin-top:15px;padding-top:15px;">
    <form method="post" id="createTest">
        <div class="form-group">
            <label for="Quiz">Tiêu đề bài thi:</label><br />
            @Html.TextBoxFor(m => m.name, new { @class = "form-control", @placeholder = "Tiêu đề" })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="Quiz">Thời gian :</label><br />
                    @Html.EnumDropDownListFor(m => m.TotalTime, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TotalTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="Quiz">Môn học:</label><br />
                    @Html.DropDownListFor(m => m.SubjectID, Model.Subject, new { @class = "form-control", @disabled="true" })
                    @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="Quiz">Trạng thái:</label><br />
                    @Html.EnumDropDownListFor(m => m.status, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="Quiz">Tổng điểm:</label><br />
                    @Html.TextBoxFor(m => m.TotalMark, new { @class = "form-control", @type = "number" })
                    @Html.ValidationMessageFor(model => model.TotalMark, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="Quiz">Chọn câu hỏi </label>
            <div class="row">
                <div class="col-md-3">
                    <label for="Quiz">Tìm theo tên :</label>
                    <input class="form-control" name="name_search" id="name_search" type="text" placeholder="Tìm kiếm câu hỏi">
                    @*<div class="spinner-border text-info" role="status">
                <span class="sr-only">Loading...</span>
            </div>*@
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="Quiz">Độ khó:</label><br />
                        @Html.EnumDropDownListFor(m => m.HardTypeChoose, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-7">
                    <p class="pull-right" id="countSelected">Đã chọn 0 câu</p>
                </div>
            </div>
            <div id="list"></div>
            @*<button type="button" class="btn btn-sm btn-block btn-info" id="button">selected</button>*@
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Cập Nhật</button>
        </div>
    </form>
</div>
<div class="modal fade" id="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Bạn có muốn đổi môn học ?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="ChangeSubjectBtn" class="btn btn-danger">Đổi</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
            </div>

        </div>
    </div>
</div>
<!--jQuery Multiselect Plugin-->
<link rel="stylesheet" type="text/css" href="~/Content/multi-select/css/picklist.min.css">
<script src="~/Content/multi-select/js/picklist.js"></script>
<script type="text/javascript">
    function updateSelectedCount() {

    }
    var pick;
    var data =
    {
            available: [

            ],
            selected: [
            ]
    };
    var confirmModal = $('#confirmModal');
    var loadData = function () {
        var subject = $('#SubjectID').val();
        var sname = $('#name_search').val();
        var hardtype = $('#HardTypeChoose').val();
        $.ajax({
            type: "POST",
            url: '/QuizTest/SearchQuiz',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ subject: subject,name : sname,hard : hardtype }),
            dataType: "json",
            success: function (recData) {
                var newavailable = [];
                recData.QuizList.forEach((e) => {
                    newavailable.push({ id: e.id, label: e.Name,hard: hardtype });
                });
                pick.pickList('updateData',newavailable);
            },
            error: function () {
                var notify = $.notify('<strong>Lỗi</strong><br/>Lỗi hệ thống<br />', {
                    type: 'pastel-warning',
                    allow_dismiss: false,
                });
            }
        });
        };
    var initialData = function () {
        var TestID = @ViewBag.id;
        $.ajax({
            type: "POST",
            url: '/QuizTest/GetQuizFromTest',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ testid: TestID }),
            dataType: "json",
            success: function (recData) {
                recData.forEach((e) => {
                    data.selected.push({ id: e.ID, label: e.name, hard: e.HardType });
                });
                pick = $('#list').pickList({
                    data: data,
                    buttons: [
                        {
                            action: 'add',
                            label: 'Thêm',
                            className: 'btn btn-sm btn-block btn-info'
                        },
                        {
                            action: 'remove',
                            label: 'Bỏ',
                            className: 'btn btn-sm btn-block btn-warning text-light'
                        },
                        {
                            action: 'removeAll',
                            label: 'Bỏ tất cả',
                            className: 'btn btn-sm btn-block btn-danger text-light'
                        }
                    ]
                });
                updateSelectedCount();
                 $('#button').on('click', function () {
                    console.log(pick.pickList('getSelected'));
                    updateSelectedCount();
                });

                pick.on('picklist.remove', function (event, v) {
                    updateSelectedCount();
                });

                pick.on('picklist.add', function (event, v) {
                    updateSelectedCount();
                });
                pick.on('picklist.removeAll', function (event, v) {
                    updateSelectedCount();
                });
            },
            error: function () {
                var notify = $.notify('<strong>Lỗi</strong><br/>Lỗi hệ thống<br />', {
                    type: 'pastel-warning',
                    allow_dismiss: false,
                });
            }
        });
    };
    $(function () {
    initialData();
    })
    $('#SubjectID').change(function () {
        if (pick.pickList('getSelected').length > 0) {
            confirmModal.find('.modal-body').text('Nếu đổi, các câu hỏi đã chọn sẽ bị reset');
            confirmModal.modal('show');
        }
        else {
            loadData();
        }
    });
    $('#name_search').keyup(() => loadData());
    $('#HardTypeChoose').change(() => loadData());
    $('#ChangeSubjectBtn').click(() => {
        loadData();
        pick.pickList('resetSelected');
        confirmModal.modal('hide');
    });

    $('#createTest').submit(function (e) {
        e.preventDefault();
        var tempdata = $(this).serializeFormJSON();
        var quizID = pick.pickList('getSelectedID').quizID;
        var data = { ...tempdata, quizID  };
        console.log(data);
        $('#overlay').fadeIn();
        $.ajax({
            type: "POST",
            url: '/QuizTest/Create',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ model: data }),
            dataType: "json",
            success: function (recData) {
                $('#overlay').fadeOut();
                if (recData.success === true) {
                    var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                        type: 'pastel-info',
                        allow_dismiss: false,
                        timer: 1000,
                    });
                }
                else {
                    var notify = $.notify('<strong>Thất bại</strong><br/>' + recData.Message + '<br />', {
                        type: 'pastel-info',
                        allow_dismiss: false,
                        timer: 1000,
                    });
                }
                setTimeout(function () {
                    window.location.href = '/QuizTest/MyQuizTest';
                }, 2000);

            },
            error: function (xhr, status, error) {
                $('#overlay').fadeOut();
                var notify = $.notify('<strong>Lỗi</strong><br/>Có lỗi xảy ra<br />', {
                    type: 'pastel-warning',
                    allow_dismiss: false,
                });
            }
        });

    });
</script>
<script>
    //JQUERY PLUGIN
    (function ($) {
    $.fn.serializeFormJSON = function () {

        var o = {};
        var a = this.serializeArray();
        $.each(a, function () {
            if (o[this.name]) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || '');
            } else {
                o[this.name] = this.value || '';
            }
        });
        return o;
    };
})(jQuery);
</script>
<script>
    function updateSelectedCount() {
        $('#countSelected').text("Đã chọn " + pick.pickList('getSelected').length + " câu.")
    }
</script>