TracNghiem/Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TracNghiem.Models
{
    public class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            QuizTest = new HashSet<QuizTest>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int QuizID { get; set; }
        [Required]
        [StringLength(100)]
        public string name { get; set; }

        [ForeignKey("Creator")]
        [Required]
        public int CreatorID { get; set; }
        public virtual User Creator { get; set; }
        [Required]
        public DateTime CreateDate { get; set; }
        [StringLength(500)]
        [Required]
        public string content { get; set; }

        [Required]
        public HardType HardType { get; set; }

        [StringLength(100)]
        public string image { get; set; }

        [ForeignKey("Subject")]
        public int SubjectID { get; set; }

        public virtual Subject Subject { get; set; }

        [StringLength(200)]
        [Required]
        public string answerA { get; set; }
        [StringLength(200)]
        [Required]
        public string answerB { get; set; }
        [StringLength(200)]
        [Required]
        public string answerC { get; set; }
        [StringLength(200)]
        [Required]
        public string answerD { get; set; }
        [Required]
        public Answer trueAnswer { get; set; }
        [Required]
        public QuizStatusAd status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizTest> QuizTest { get; set; }

    }
    
}

TracNghiem/Controllers/QuizController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;
using TracNghiem.ViewModel;

namespace TracNghiem.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        QuizContext db = new QuizContext();
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Quản lý môn học
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles ="admin")]
        public ViewResult SubjectManager()
        {
            var result = (from s in db.Subjects
                          where s.status == CommonStatus.active
                         select new SubjectViewModel
                         {
                             ID = s.ID,
                             SubjectName = s.name,
                             QuizCount = s.Quizzes.Count(),
                             QuizTestCount = s.QuizTests.Count()
                         }).ToList();
            return View(result);
        }
        /// <summary>
        /// Xóa môn học AJAX
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public JsonResult DeleteSubject(int id)
        {
            Subject s = db.Subjects.Find(id);
            s.status = CommonStatus.notactive;
            db.SaveChanges();
            return Json(new { Message = "Xóa thành công" }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Sửa môn học
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        public JsonResult EditSubject(int id, string name)
        {
            Subject s = db.Subjects.Find(id);
            s.name = name;
            db.SaveChanges();
            return Json(new { Message = "Sửa thành công" }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Sửa môn học
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public JsonResult AddSubject(string name)
        {
            Subject s = new Subject { name = name, status = CommonStatus.active };
            db.Subjects.Add(s);
            db.SaveChanges();
            return Json(new { Message = "Thêm thành công" }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Tất cả câu hỏi
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="CurrentSort"></param>
        /// <param name="page"></param>
        /// <param name="titleStr"></param>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public ViewResult AllQuiz(string sortOrder, string CurrentSort, int? page, string titleStr)
        {
            int pageSize = 100;
            int pageIndex = 1;
            ViewBag.Sort = "tăng dần";
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "Title" : sortOrder;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<QuizViewModelAd> lstQuiz = null;
            var id = db.Users.Where(e => e.username == User.Identity.Name).First().ID;
            if (String.IsNullOrWhiteSpace(titleStr))
            {
                switch (sortOrder)
                {
                    case "title":
                        lstQuiz = db.Quizzes.Where(a=>a.status != QuizStatusAd.NotActive).OrderBy(e => e.name).Select(q =>
                        new QuizViewModelAd
                        {
                            status = q.status,
                            ID = q.QuizID,
                            name = q.name,
                            HardType = q.HardType,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                    case "createdate":
                        lstQuiz = db.Quizzes.Where(a => a.status != QuizStatusAd.NotActive).OrderBy(e => e.CreateDate).Select(q =>
                        new QuizViewModelAd
                        {
                            status = q.status,
                            ID = q.QuizID,
                            name = q.name,
                            HardType = q.HardType,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                    default:
                        lstQuiz = db.Quizzes.Where(a => a.status != QuizStatusAd.NotActive).OrderBy(e => e.name).Select(q =>
                        new QuizViewModelAd
                        {
                            status = q.status,
                            ID = q.QuizID,
                            name = q.name,
                            HardType = q.HardType,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }
                        ).ToPagedList(pageIndex, pageSize);
                        break;
                }
            }
            else
            {
                ViewBag.titleStr = titleStr;
                switch (sortOrder)
                {
                    case "title":
                        ViewBag.sortname = "tiêu đề";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            lstQuiz = db.Quizzes.Where(t => t.name.Contains(titleStr) && t.status != QuizStatusAd.NotActive).OrderBy(e => e.name).Select(q =>
                           new QuizViewModelAd
                           {
                               status = q.status,
                               ID = q.QuizID,
                               name = q.name,
                               HardType = q.HardType,
                               SubjectName = q.Subject.name,
                               CreatorName = q.Creator.username,
                               CreateDate = q.CreateDate,
                           }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        else
                        {
                            lstQuiz = db.Quizzes.Where(t => t.name.Contains(titleStr) && t.status != QuizStatusAd.NotActive).OrderByDescending(e => e.name).Select(q =>
                            new QuizViewModelAd
                            {
                                status = q.status,
                                ID = q.QuizID,
                                name = q.name,
                                HardType = q.HardType,
                                SubjectName = q.Subject.name,
                                CreatorName = q.Creator.username,
                                CreateDate = q.CreateDate,
                            }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    case "createdate":
                        ViewBag.sortname = "ngày tạo";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            lstQuiz = db.Quizzes.Where(t => t.name.Contains(titleStr) && t.status != QuizStatusAd.NotActive).OrderBy(e => e.CreateDate).Select(q =>
                            new QuizViewModelAd
                            {
                                status = q.status,
                                ID = q.QuizID,
                                name = q.name,
                                HardType = q.HardType,
                                SubjectName = q.Subject.name,
                                CreatorName = q.Creator.username,
                                CreateDate = q.CreateDate,
                            }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        else
                        {
                            lstQuiz = db.Quizzes.Where(t => t.name.Contains(titleStr) && t.status != QuizStatusAd.NotActive).OrderByDescending(e => e.CreateDate).Select(q =>
                            new QuizViewModelAd
                            {
                                status = q.status,
                                ID = q.QuizID,
                                name = q.name,
                                HardType = q.HardType,
                                SubjectName = q.Subject.name,
                                CreatorName = q.Creator.username,
                                CreateDate = q.CreateDate,
                            }
                            ).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    default:
                        lstQuiz = db.Quizzes.Where(t => t.name.Contains(titleStr) && t.status != QuizStatusAd.NotActive).OrderBy(e => e.name).Select(q =>
                        new QuizViewModelAd
                        {
                            status = q.status,
                            ID = q.QuizID,
                            name = q.name,
                            HardType = q.HardType,
                            SubjectName = q.Subject.name,
                            CreatorName = q.Creator.username,
                            CreateDate = q.CreateDate,
                        }

TracNghiem/Views/Quiz/AllQuiz.cshtml
@model PagedList.IPagedList<TracNghiem.ViewModel.QuizViewModelAd>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Kho câu hỏi - Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.css" rel="stylesheet" />

<div style="margin-top:10px;"></div>

<div class="row">

    <div class="col-12">
        <div class="card">
            <div style="padding: 0.75rem 1.25rem;">
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div>
                            <label style="display:inline-block;font-weight:normal">Sắp xếp theo <b>@ViewBag.sortname</b> @ViewBag.Sort</label>
                        </div>
                        @Html.ActionLink("Tiêu đề", "MyQuiz", new { sortOrder = "title", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                        @Html.ActionLink("Ngày tạo", "MyQuiz", new { sortOrder = "createdate", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                    </div>
                    <div class="col-sm-12 col-md-4">
                        @using (Html.BeginForm("MyQuiz", "Quiz", FormMethod.Get, new { enctype = "multipart/form-data" }))
                        {
                            <label style="display:inline-block;font-weight:normal;">
                                Tìm theo tiêu đề:
                                <input name="titleStr" type="search" value="@(ViewBag.titleStr as string)" class="form-control">
                            </label>
                            <label style="display:inline-block;font-weight:normal;">
                                <input style="margin-top:-4.4px" class="btn btn-info" type="submit" value="Tìm kiếm" />
                            </label>
                        }

                    </div>
                    <div class="col-md-1">
                        <br />
                        <a href="/Quiz/MyQuiz" style="font-size: 14px;font-weight: normal;padding: .8em;" class="badge badge-danger">RESET bộ lọc</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">

        <div class="card">
            <div class="card-header">
                @if (Model.PageNumber > 1)
                {
                    <h3 class="card-title">
                        100 câu hỏi thứ @Model.PageNumber
                    </h3>
                }
                else
                {
                    <h3 class="card-title">
                        100 câu hỏi đầu tiên
                    </h3>
                }
            </div>
            <div class="card-body">
                <table id="lstPost" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên câu hỏi</th>
                            <th>Độ khó</th>
                            <th>Môn học</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <p>@item.ID</p>
                                </td>
                                <td>
                                    @item.name
                                </td>
                                <td>
                                    @item.HardType
                                </td>
                                <td>
                                    @item.SubjectName
                                </td>
                                <td>
                                    @String.Format("{0:dd/MM/yyyy}", item.CreateDate)
                                </td>
                                <td>
                                    <label class="switch">
                                        <input onchange="changeStt(this)" type="checkbox" id="@item.ID" @(item.status == TracNghiem.Models.QuizStatusAd.Active ? "checked" : "") class="success">
                                        <span class="slider"></span>
                                    </label>
                                </td>
                                <td>
                                    @{
                                        if (User.Identity.Name == item.CreatorName || User.IsInRole("admin"))
                                        {
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new { @class = "badge badge-primary" })
                                            <a onclick="deleteConfirm(@item.ID,'@item.name')" href="#" class="badge badge-danger">Xóa</a>

                                        }
                                    }

                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Tên câu hỏi</th>
                            <th>Độ khó</th>
                            <th>Môn học</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
@{
    if (Model.PageCount > 1)
    {
        <nav aria-label="Page navigation example" style="text-align:center">
            @Html.PagedListPager(Model, page => Url.Action("MyQuiz", new { page, sortOrder = Request.Params["sortOrder"], CurrentSort = Request.Params["CurrentSort"], titleStr = ViewBag.titleStr }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
        </nav>
    }
}
<!-- The delete Modal -->
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Bạn có muốn xóa câu hỏi ?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="deleteBtn" class="btn btn-danger">Xóa</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="~/Content/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.min.js"></script>

<script>
$(function () {
    $("#lstPost").DataTable();
});
var delmodal = $('#deleteModal');
var idx;
var deleteConfirm = function (id, title) {
    idx = id;
    delmodal.find('.modal-body').text(title);
    delmodal.modal('show');

}
$('#deleteBtn').click(function () {
    delmodal.modal('hide');
    $.ajax({
        type: "POST",
        url: '/Quiz/DeleteQuiz',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({ id: idx }),
        dataType: "json",
        success: function (recData) {
            var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                type: 'pastel-info',
                allow_dismiss: false,
                timer: 1000,
            });
            setTimeout(function () {
                window.location.reload();
            }, 2000);

        },
        error: function () {
            var notify = $.notify('<strong>Lỗi</strong><br/>Không xóa được<br />', {
                type: 'pastel-warning',
                allow_dismiss: false,
            });
        }
    });
});
var changeStt = function (xthis) {
    var xid = xthis.id;
    var st = xthis.checked ? 1 : 0;
    $.ajax({
        type: "POST",
        url: '/Quiz/ChangeStatus',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({ id: xid, state: st }),
        dataType: "json",
        success: function (recData) {
            var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                type: 'pastel-info',
                allow_dismiss: false,
                timer: 1000,
            });
        },
        error: function () { alert('An error occured'); }
    });
}
</script>

TracNghiem/Views/Quiz/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

TracNghiem/Views/Quiz/MyQuiz.cshtml
@model PagedList.IPagedList<TracNghiem.ViewModel.QuizViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Kho câu hỏi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.css" rel="stylesheet" />

<div style="margin-top:10px;"></div>

<div class="row">

    <div class="col-12">
            <div class="card">
                <div style="padding: 0.75rem 1.25rem;">
                    <div class="row">
                        <div class="col-sm-12 col-md-5">
                            <div>
                                <label style="display:inline-block;font-weight:normal">Sắp xếp theo <b>@ViewBag.sortname</b> @ViewBag.Sort</label>
                            </div>
                            @Html.ActionLink("Tiêu đề", "MyQuiz", new { sortOrder = "title", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                            @Html.ActionLink("Ngày tạo", "MyQuiz", new { sortOrder = "createdate", CurrentSort = ViewBag.CurrentSort, titleStr = ViewBag.titleStr }) |
                        </div>
                        <div class="col-sm-12 col-md-4">
                            @using (Html.BeginForm("MyQuiz", "Quiz", FormMethod.Get, new { enctype = "multipart/form-data" }))
                            {
                                <label style="display:inline-block;font-weight:normal;">
                                    Tìm theo tiêu đề:
                                    <input name="titleStr" type="search" value="@(ViewBag.titleStr as string)" class="form-control">
                                </label>
                                <label style="display:inline-block;font-weight:normal;">
                                    <input style="margin-top:-4.4px" class="btn btn-info" type="submit" value="Tìm kiếm" />
                                </label>
                            }

                        </div>
                        <div class="col-md-3">
                            <br />
                            <a href="/Quiz/MyQuiz" style="font-size: 14px;font-weight: normal;padding: .8em;" class="badge badge-danger">RESET bộ lọc</a>
                            <a href="/Quiz/Create" style="font-size: 14px;font-weight: normal;padding: .8em;" class="badge badge-info">Thêm câu hỏi</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="col-12">

        <div class="card">
            <div class="card-header">
                @if (Model.PageNumber > 1)
                {
                    <h3 class="card-title">
                        100 câu hỏi thứ @Model.PageNumber
                    </h3>
                }
                else
                {
                    <h3 class="card-title">
                        100 câu hỏi đầu tiên
                    </h3>
                }
            </div>
            <div class="card-body">
                <table id="lstPost" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên câu hỏi</th>
                            <th>Độ khó</th>
                            <th>Môn học</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <p>@item.ID</p>
                                </td>
                                <td>
                                    @item.name
                                </td>
                                <td>
                                    @item.HardType
                                </td>
                                <td>
                                    @item.SubjectName
                                </td>
                                <td>
                                    @String.Format("{0:dd/MM/yyyy}", item.CreateDate)
                                </td>
                                <td>
                                    <label class="switch">
                                        <input onchange="changeStt(this)" type="checkbox" id="@item.ID" @(item.status == TracNghiem.Models.QuizStatus.Active ? "checked" : "") class="success">
                                        <span class="slider"></span>
                                    </label>
                                </td>
                                <td>
                                    @{
                                        if (User.Identity.Name == item.CreatorName || User.IsInRole("admin"))
                                        {
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new { @class = "badge badge-primary" })
                                            <a onclick="deleteConfirm(@item.ID,'@item.name')" href="#" class="badge badge-danger">Xóa</a>

                                        }
                                    }

                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Tên câu hỏi</th>
                            <th>Độ khó</th>
                            <th>Môn học</th>
                            <th>Ngày tạo</th>
                            <th>Hiển thị</th>
                            <th>Hành động</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
@{
    if (Model.PageCount > 1)
    {
        <nav aria-label="Page navigation example" style="text-align:center">
            @Html.PagedListPager(Model, page => Url.Action("MyQuiz", new { page, sortOrder = Request.Params["sortOrder"], CurrentSort = Request.Params["CurrentSort"], titleStr = ViewBag.titleStr }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
        </nav>
    }
}
<!-- The delete Modal -->
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Bạn có muốn xóa câu hỏi ?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="deleteBtn" class="btn btn-danger">Xóa</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="~/Content/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Content/AdminLTE/plugins/datatables/dataTables.bootstrap4.min.js"></script>

<script>
$(function () {
    $("#lstPost").DataTable();
});
var delmodal = $('#deleteModal');
var idx;
var deleteConfirm = function (id, title) {
    idx = id; 
    delmodal.find('.modal-body').text(title);
    delmodal.modal('show');
   
}
$('#deleteBtn').click(function () {
    delmodal.modal('hide');
    $.ajax({
        type: "POST",
        url: '/Quiz/DeleteQuiz',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({ id: idx }),
        dataType: "json",
        success: function (recData) {
            var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                type: 'pastel-info',
                allow_dismiss: false,
                timer: 1000,
            });
            setTimeout(function () {
                window.location.reload();
            }, 2000);

        },
        error: function () {
            var notify = $.notify('<strong>Lỗi</strong><br/>Không xóa được<br />', {
                type: 'pastel-warning',
                allow_dismiss: false,
            });
        }
    });
});
var changeStt = function (xthis) {
    var xid = xthis.id;
    var st = xthis.checked ? 1 : 0;
    $.ajax({
        type: "POST",
        url: '/Quiz/ChangeStatus',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({ id: xid, state: st }),
        dataType: "json",
        success: function (recData) {
            var notify = $.notify('<strong>Thành công</strong><br/>' + recData.Message + '<br />', {
                type: 'pastel-info',
                allow_dismiss: false,
                timer: 1000,
            });
        },
        error: function () { alert('An error occured'); }
    });
}
</script>